/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as tslib_1 from "tslib";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { TokenApiClientContext } from "./tokenApiClientContext";
var TokenApiClient = /** @class */ (function (_super) {
    tslib_1.__extends(TokenApiClient, _super);
    /**
     * Initializes a new instance of the TokenApiClient class.
     * @param credentials Subscription credentials which uniquely identify client subscription.
     * @param [options] The parameter options
     */
    function TokenApiClient(credentials, options) {
        var _this = _super.call(this, credentials, options) || this;
        _this.botSignIn = new operations.BotSignIn(_this);
        _this.userToken = new operations.UserToken(_this);
        return _this;
    }
    return TokenApiClient;
}(TokenApiClientContext));
// Operation Specifications
export { TokenApiClient, TokenApiClientContext, Models as TokenApiModels, Mappers as TokenApiMappers };
export * from "./operations";
//# sourceMappingURL=tokenApiClient.js.map