/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
export var channelId = {
    parameterPath: [
        "options",
        "channelId"
    ],
    mapper: {
        serializedName: "channelId",
        type: {
            name: "String"
        }
    }
};
export var code = {
    parameterPath: [
        "options",
        "code"
    ],
    mapper: {
        serializedName: "code",
        type: {
            name: "String"
        }
    }
};
export var codeChallenge = {
    parameterPath: [
        "options",
        "codeChallenge"
    ],
    mapper: {
        serializedName: "code_challenge",
        type: {
            name: "String"
        }
    }
};
export var connectionName0 = {
    parameterPath: "connectionName",
    mapper: {
        required: true,
        serializedName: "connectionName",
        type: {
            name: "String"
        }
    }
};
export var connectionName1 = {
    parameterPath: [
        "options",
        "connectionName"
    ],
    mapper: {
        serializedName: "connectionName",
        type: {
            name: "String"
        }
    }
};
export var emulatorUrl = {
    parameterPath: [
        "options",
        "emulatorUrl"
    ],
    mapper: {
        serializedName: "emulatorUrl",
        type: {
            name: "String"
        }
    }
};
export var finalRedirect = {
    parameterPath: [
        "options",
        "finalRedirect"
    ],
    mapper: {
        serializedName: "finalRedirect",
        type: {
            name: "String"
        }
    }
};
export var include = {
    parameterPath: [
        "options",
        "include"
    ],
    mapper: {
        serializedName: "include",
        type: {
            name: "String"
        }
    }
};
export var state = {
    parameterPath: "state",
    mapper: {
        required: true,
        serializedName: "state",
        type: {
            name: "String"
        }
    }
};
export var userId = {
    parameterPath: "userId",
    mapper: {
        required: true,
        serializedName: "userId",
        type: {
            name: "String"
        }
    }
};
//# sourceMappingURL=parameters.js.map