/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */
import * as msRest from "@azure/ms-rest-js";
import * as Mappers from "../models/botSignInMappers";
import * as Parameters from "../models/parameters";
/** Class representing a BotSignIn. */
var BotSignIn = /** @class */ (function () {
    /**
     * Create a BotSignIn.
     * @param {TokenApiClientContext} client Reference to the service client.
     */
    function BotSignIn(client) {
        this.client = client;
    }
    BotSignIn.prototype.getSignInUrl = function (state, options, callback) {
        return this.client.sendOperationRequest({
            state: state,
            options: options
        }, getSignInUrlOperationSpec, callback);
    };
    return BotSignIn;
}());
export { BotSignIn };
// Operation Specifications
var serializer = new msRest.Serializer(Mappers);
var getSignInUrlOperationSpec = {
    httpMethod: "GET",
    path: "api/botsignin/GetSignInUrl",
    queryParameters: [
        Parameters.state,
        Parameters.codeChallenge,
        Parameters.emulatorUrl,
        Parameters.finalRedirect
    ],
    responses: {
        200: {
            bodyMapper: {
                serializedName: "parsedResponse",
                type: {
                    name: "String"
                }
            }
        },
        default: {}
    },
    serializer: serializer
};
//# sourceMappingURL=botSignIn.js.map