name: test-compat.yml

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - '4.12'
    - '4.13'
  pull_request:
    branches:
    - main
    - '4.12'
    - '4.13'

jobs:
  ci:
    name: test:compat
    runs-on: ubuntu-latest

    timeout-minutes: 10
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]
        node-version: [22.X]

    steps:
      - uses: actions/checkout@v2

      - name: use node ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: yarn
        run: yarn --frozen-lockfile

      - name: yarn build
        run: yarn build

      - name: yarn test:compat
        run: yarn test:compat
